- name: install venv and others
  become: true
  apt:
    name:
      - python3-venv
      - python-is-python3
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install python compile-dependencies
  become: true
  apt:
    name:
      - build-essential
      - make
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install python poetry
  shell:
    cmd: curl -sSL https://install.python-poetry.org | python3 -
    creates: ~/.local/bin/poetry
