- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- name: install zoxide from github
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -o /usr/local/bin/stew -L https://github.com/marwanhawari/stew/releases/download/v{{ git_versions.stew }}/stew-{{ ansible_system | lower }}-{{ arch_map[ansible_architecture] }}
      chmod +x /usr/local/bin/stew
    creates: /usr/local/bin/stew
  when: ansible_architecture != "MacOSX"
