- name: install git tools
  become: true
  apt:
    name:
      - git-extras
      - git-crypt
      - git-lfs
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install 'git-delta' from cargo
  environment:
    PATH: "{{ home_path }}/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: cargo install --locked git-delta
    creates: ~/.cargo/bin/delta

- name: install glab from snap
  become: true
  community.general.snap:
    name: glab
    channel: latest/edge
  register: glab

- name: allow glab to access ssh-keys
  become: true
  shell:
    cmd: snap connect glab:ssh-keys
  when: glab.changed
