version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
    assignees:
      - "konradmalik"

  - package-ecosystem: "terraform"
    directories:
      - "/cloud/*"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        patterns: ["*"]
    assignees:
      - "konradmalik"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:00"
      timezone: "Europe/Warsaw"
    groups:
      flake:
        patterns: ["*"]
    assignees:
      - "konradmalik"
