version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/cloud/aws"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/cloud/backblaze"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/cloud/cloudflare"
    schedule:
      interval: "weekly"
