- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: ubuntu-aarch64.yaml
  when: ansible_architecture == "aarch64"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link neovim config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - neovim

- name: headless neovim autoinstall
  timeout: 300 # seconds
  # the first one initializes packer
  # the second one installs all plugins
  # the third one compiles all treesitter parsers
  shell:
    cmd: |
      nvim --headless -c 'qa'
      nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
      nvim --headless -c 'TSUpdateSync' -c 'qa'
