- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: ubuntu-aarch64.yaml
  when: ansible_architecture == "aarch64"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link neovim config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - neovim

# stylua for lua formatting (for neovim configs etc.)
- name: install neovim plugin deps from cargo
  args:
    executable: /bin/bash
  shell:
    cmd: |
      source ~/.cargo/env && \
      cargo install stylua
