- name: install fuse for neovim from appimage
  become: yes
  apt:
    name:
      - libfuse2
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install neovim from appimage
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -o /usr/local/bin/nvim -L https://github.com/neovim/neovim/releases/download/v{{ git_versions.nvim }}/nvim.appimage
      chmod +x /usr/local/bin/nvim
    creates: /usr/local/bin/nvim
  when: ansible_architecture == "x86_64"

- name: install prettier globally
  become: yes
  community.general.npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - prettier

- name: install shfmt binary
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -o /usr/local/bin/shfmt -L https://github.com/mvdan/sh/releases/download/v{{ git_versions.shfmt }}/shfmt_v{{ git_versions.shfmt }}_linux_{{ arch_map[ansible_architecture] }}
      chmod +x /usr/local/bin/shfmt
    creates: /usr/local/bin/shfmt
