- name: install fuse for neovim from appimage
  become: true
  apt:
    name:
      - libfuse2
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install neovim from appimage
  become: true
  shell:
    chdir: /tmp
    cmd: |
      curl -o nvim -L https://github.com/neovim/neovim/releases/download/v{{ git_versions.nvim }}/nvim.appimage
      install nvim /usr/local/bin/
    creates: /usr/local/bin/nvim
  when: ansible_architecture == "x86_64"
