- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: make sure ssh folder has proper mode
  file:
    path: ~/.ssh
    state: directory
    mode: "0700"

- name: get authorized_keys from github
  ansible.builtin.get_url:
    url: https://github.com/konradmalik.keys
    #url: https://gitlab.com/konradmalik.keys
    # dest requires absolute path
    dest: "{{ home_path }}/.ssh/authorized_keys"
    force: true
    mode: "0600"

# use block to become: true for all inside
- block:
    - name: Disable root SSH login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present

    - name: Disable SSH password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present

    # UFW Setup
    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH
      when: ansible_distribution == "Ubuntu"

    - name: UFW - Deny all other incoming traffic by default (all but raspberry pis)
      ufw:
        state: enabled
        policy: deny
        direction: incoming
      when:
        - ansible_distribution == "Ubuntu"
        - "'rpis' not in group_names"

    - name: start and enable ssh daemon
      service:
        name: sshd
        state: started
        enabled: yes

  become: true
  when: ansible_system == "Linux"
