- name: install git tools
  become: yes
  apt:
    name:
      - git-extras
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install delta from github
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -o delta.deb -L https://github.com/dandavison/delta/releases/download/{{ git_versions.git_delta }}/git-delta_{{ git_versions.git_delta }}_{{ arch_map[ansible_architecture] }}.deb
      dpkg -i delta.deb
      rm -rf delta.deb
    creates: /usr/bin/delta
