- name: install apt packages for auto updates
  become: true
  apt:
    name:
      - unattended-upgrades
      - update-notifier-common
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | sudo debconf-set-selections  - auto install security updates
  become: true
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: "true"
- name: apt install unattended-upgrades
  become: true
  apt:
    name: unattended-upgrades
- name: dpkg-reconfigure -f noninteractive unattended-upgrades
  become: true
  command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    creates: /etc/apt/apt.conf.d/20auto-upgrades

- block:
    - name: Enable auto reboot after update
      become: true
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: 'Unattended-Upgrade::Automatic-Reboot "false";'
        line: 'Unattended-Upgrade::Automatic-Reboot "true";'
    - name: Set auto reboot to 2 am
      become: true
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: "Unattended-Upgrade::Automatic-Reboot-Time"
        line: 'Unattended-Upgrade::Automatic-Reboot-Time "02:00";'
  when: enable_auto_reboot
