version: "3"

services:
  pihole:
    image: pihole/pihole:2022.04.3
    container_name: pihole
    hostname: pi.hole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "Europe/Warsaw"
      WEBPASSWORD: "konrad1"
      FTLCONF_REPLY_ADDR4: "192.168.0.3"
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1;8.8.8.8;8.8.4.4"
      DNSMASQ_LISTENING: "all"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - pihole-etc-data:/etc/pihole/
      - pihole-etc-dnsmasq:/etc/dnsmasq.d/
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G

volumes:
  pihole-etc-data:
  pihole-etc-dnsmasq:
