- name: install asdf from git
  shell:
    chdir: /tmp
    cmd: |
      git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v{{ git_versions.asdf }} --depth 1
    creates: ~/.asdf

- name: link asdf and direnv config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="{{ home_path }}/.config/" {{ item }}
  with_items:
    - direnv

- block:
    - name: Check that the completion file exists
      stat:
        path: "~/.asdf/completions/_asdf"
      register: stat_result

    - name: link asdf completion
      ansible.builtin.file:
        src: "~/.asdf/completions/_asdf"
        path: "{{ zdotdir }}/zfunc/_asdf"
        state: link
        force: yes
      when: stat_result.stat.exists

- name: install asdf direnv plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add direnv
    creates: ~/.asdf/plugins/direnv
