- name: install podman
  become: yes
  apt:
    pkg:
      - podman
    state: present

- name: install dive from github
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -o dive.deb -L https://github.com/wagoodman/dive/releases/download/v{{ git_versions.dive }}/dive_{{ git_versions.dive }}_linux_{{ arch_map[ansible_architecture] }}.deb
      dpkg -i dive.deb
      rm -rf dive.deb
    creates: /usr/local/bin/dive
  when: ansible_architecture == "x86_64"
