- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: check bashrc stat
  stat:
    path: "{{ home_path }}/.bashrc"
  register: link

- name: remove bashrc if not linked yet
  ansible.builtin.file:
    path: "{{ home_path }}/.bashrc"
    state: absent
  when: link.stat.islnk is not defined or not link.stat.islnk

- name: link zsh and bash config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="{{ home_path }}/.config/" {{ item }}
  with_items:
    - zsh
    - bash

- name: change shell to zsh for "{{ target_user }}"
  become: true
  user:
    name: "{{ target_user }}"
    shell: /bin/zsh
  when: ansible_system == "Linux"

- name: makes sure zfunc exists (sets it up for the later tasks)
  file:
    path: "~/.config/zsh/zfunc"
    state: directory
