- name: make sure 'Code' exists and belongs to "{{ target_user }}"
  become: true
  ansible.builtin.file:
    path: "{{ home_path }}/Code/github.com/konradmalik"
    state: directory
    mode: "0755"
    recurse: no
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Ensure dotfiles repo exists
  become: false
  ansible.builtin.git:
    repo: https://github.com/konradmalik/dotfiles.git
    dest: "{{ repo_path }}"
    version: main
    recursive: false
    clone: true
    force: true
    update: true
