- name: make sure 'Code' exists and belongs to "{{ target_user }}"
  become: true
  ansible.builtin.file:
    path: "{{ home_path }}/Code"
    state: directory
    mode: "0755"
    recurse: no
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Ensure dotfiles repo exists (public)
  ansible.builtin.git:
    repo: https://github.com/konradmalik/dotfiles.git
    dest: "{{ home_path }}/Code/dotfiles"
    version: main
    recursive: false
    clone: true
    force: true
    update: true
  when: not private_machine

- name: Ensure dotfiles repo exists (private)
  ansible.builtin.git:
    repo: git@github.com:konradmalik/dotfiles.git
    dest: "{{ home_path }}/Code/dotfiles"
    version: main
    recursive: true
    clone: true
    force: true
    update: true
  when: private_machine
