- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link tmux config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$XDG_CONFIG_HOME"{{ item }}
  with_items:
    - tmux

- name: install tpm
  shell:
    cmd: git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
    creates: ~/.config/tmux/plugins/tpm

- name: install all tpm plugins
  shell:
    cmd: |
      ~/.config/tmux/plugins/tpm/bin/install_plugins
      ~/.config/tmux/plugins/tpm/bin/update_plugins all
    creates: ~/.config/tmux/plugins/tmux-mode-indicator
