- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link tmux config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - tmux

- name: install tpm
  shell:
    cmd: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  creates: ~/.tmux/plugins/tpm

- name: install all tpm plugins
  shell:
    cmd: |
      ~/.tmux/plugins/tpm/bin/install_plugins
      ~/.tmux/plugins/tpm/bin/update_plugins all
  creates: ~/.tmux/plugins/tmux-sensible
