- name: install docker packages from aur
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - docker
      - docker-compose
      - docker-credential-pass
      - dive
      - nerdctl-git
