- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: make sure /etc/docker exists
  become: true
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: disabling userland-proxy
  become: true
  ansible.builtin.copy:
    dest: "/etc/docker/daemon.json"
    content: '{"userland-proxy": true}'

- name: enable docker daemon (dont start yet)
  become: true
  service:
    name: docker
    state: stopped
    enabled: yes
  when:
    - ansible_system == "Linux"

- block:
    - name: Create "docker" group
      group:
        name: docker
        state: present

    - name: adding existing user "{{ target_user }}" to group "docker"
      user:
        name: "{{ target_user }}"
        groups: [docker]
        append: yes

  become: true
  when:
    - ansible_system == "Linux"
