- name: add docker apt key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"
    force: true

- name: add docker apt repo
  become: true
  apt_repository:
    repo: "deb [arch={{ arch_map[ansible_architecture] }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: install docker and it's dependencies
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - docker-compose-plugin
    state: present

- name: install nerdctl from github
  become: true
  shell:
    chdir: /tmp
    cmd: |
      curl -L https://github.com/containerd/nerdctl/releases/download/v{{ git_versions.nerdctl }}/nerdctl-{{ git_versions.nerdctl }}-linux-{{ arch_map[ansible_architecture] }}.tar.gz | tar xvfz -
      install nerdctl /usr/local/bin/
    creates: /usr/local/bin/nerdctl
