- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"
