- name: Upgrade all apt packages
  become: yes
  apt:
    upgrade: dist
    force_apt_get: yes
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install apt packages
  become: yes
  apt:
    name:
      - gpg-agent
      - git
      - unzip
      - pip
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes
