- name: Upgrade all apt packages
  become: true
  apt:
    upgrade: dist
    force_apt_get: yes
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install apt packages
  become: true
  apt:
    name:
      - curl
      - rustc
      - cargo
      - wget
      - git
      - unzip
      - cmake
      - python-is-python3
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes
