- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link configs
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="{{ home_path }}/.config/" {{ item }}
  with_items:
    - i3
    - Xresources
    - rofi
    - xinitrc
    - feh
    - picom
