- name: install clipboard apt packages
  become: true
  apt:
    name:
      - xclip
      - wl-clipboard
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: add regolith apt key
  become: true
  shell:
    chdir: /tmp
    cmd: |
      curl -sL https://regolith-desktop.org/regolith.key |
        gpg --dearmor |
        tee /etc/apt/trusted.gpg.d/regolith.asc > /dev/null
    creates: /etc/apt/trusted.gpg.d/regolith.asc

- name: add regolith apt repo
  become: true
  apt_repository:
    repo: "deb [arch={{ arch_map[ansible_architecture] }}] https://regolith-desktop.org/release-ubuntu-{{ ansible_distribution_release }}-{{ arch_map[ansible_architecture] }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: install regolith apt packages
  become: true
  apt:
    name:
      - regolith-desktop
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes
