version: "3"

services:
  pihole:
    image: pihole/pihole:2022.05
    container_name: pihole
    hostname: pi1.hole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "Europe/Warsaw"
      WEBPASSWORD: "konrad1"
      FTLCONF_REPLY_ADDR4: "192.168.0.2"
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1;8.8.8.8;8.8.4.4"
      DNSMASQ_LISTENING: "all"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - pihole-etc-data:/etc/pihole/
      - pihole-etc-dnsmasq:/etc/dnsmasq.d/
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G

  portainer:
    image: portainer/portainer-ce:2.13.1-alpine
    ports:
      - "9443:9443/tcp"
      - "8000:8000/tcp"
    environment:
      TZ: "Europe/Warsaw"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G

  rpi-spotify:
    image: konradmalik/librespot:0.3.1
    network_mode: host
    devices: [/dev/snd]
    environment:
      TZ: "Europe/Warsaw"
    command: >
      librespot
        --name Raspotify
        --bitrate 320
        --enable-volume-normalisation
        --disable-audio-cache
        --initial-volume 35

    deploy:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "1"
          memory: 1G

  shairport-sync:
    image: mikebrady/shairport-sync:3.3.8
    network_mode: host
    command: -v
    devices: [/dev/snd]
    environment:
      TZ: "Europe/Warsaw"
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "1"
          memory: 1G

volumes:
  portainer-data:
  pihole-etc-data:
  pihole-etc-dnsmasq:
