- block:
    - name: add hashicorp apt key
      become: yes
      shell:
        chdir: /tmp
        cmd: |
          curl -sL https://apt.releases.hashicorp.com/gpg |
            gpg --dearmor |
            tee /etc/apt/trusted.gpg.d/hashicorp.gpg > /dev/null
        creates: /etc/apt/trusted.gpg.d/hashicorp.gpg

    - name: add hashicorp apt repo (amd64)
      become: yes
      apt_repository:
        repo: "deb [arch={{ arch_map[ansible_architecture] }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
  when: ansible_architecture == "x86_64"

- name: add microsoft apt key
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -sL https://packages.microsoft.com/keys/microsoft.asc |
        gpg --dearmor |
        tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
    creates: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: add microsoft azure cli apt repo (amd64)
  become: yes
  apt_repository:
    repo: "deb [arch={{ arch_map[ansible_architecture] }}] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: install azure cli
  become: yes
  apt:
    pkg:
      - azure-cli
    state: present

- name: install awscli
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -L "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      ./aws/install
    creates: /usr/local/aws-cli
