- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- name: set default toolchain
  environment:
    PATH: "{{ home_path }}/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      rustup install stable \
      && rustup default stable
