all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # specify user for which this whole playbook should run
    target_user: "{{ lookup('env','USER') or 'konrad' }}"
    # for ssh-ingress if below is enabled
    enable_ssh: true
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/private.pub') }}"
    # path to dotfiles repository on a host (I assume all hosts are linux machines)
    repo_path: "/home/{{ target_user }}/Code/dotfiles"
    # zsh files dir (same as in zshenv)
    zdotdir: "~/.config/zsh"
    # if true - assumes installation in a docker-container
    # some apps will be disabled, like the docker daemon itself
    docker: false
    # if enabled - some gui only apps will be installed as well
    gui_apps: false
    # if enabled, ssh config will be linked (outbound ssh)
    private_machine: false
    # if true, will autoreboot at 2 am after automatic updates
    enable_auto_reboot: false
    # if enabled, will setup stuff needed to properly work inside a vmware guest
    vmware_guest: false
    # versions used mostly by ubuntu tasks that install stuff from github directly
    git_versions:
      asdf: 0.10.2
      dive: 0.10.0
      dsq: 0.22.0
      duf: 0.8.1
      k9s: 0.26.3
      nerdctl: 0.22.2
      nvim: 0.7.2
      shfmt: 3.5.1
      sshocker: 0.3.0
      tinygo: 0.25.0
      viddy: 0.3.6
    # Mappings from Ansible reported architecture to distro release architecture
    arch_map:
      x86_64: amd64
      ppc64le: ppc64el
      s390x: s390x
      armv7l: armhf
      aarch64: arm64

lima:
  hosts:
    devarch:
  vars:
    ansible_connection: local
    docker: true
    enable_auto_reboot: false
    enable_ssh: false
    gui_apps: false
    repo_path: "/home/{{ target_user }}.linux/Code/dotfiles"
    private_machine: true
    vmware_guest: false

cicd:
  hosts:
    limavm:
  vars:
    ansible_connection: local
    docker: false
    enable_auto_reboot: false
    enable_ssh: false
    gui_apps: false
    repo_path: "/home/{{ target_user }}.linux/Code/dotfiles"
    private_machine: false
    vmware_guest: false

local:
  hosts:
    localhost:
  vars:
    ansible_connection: local
    docker: false
    enable_auto_reboot: false
    enable_ssh: false
    gui_apps: false
    private_machine: true
    vmware_guest: false

docker:
  hosts:
    devarchd:
  vars:
    ansible_connection: local
    docker: true
    enable_auto_reboot: false
    enable_ssh: false
    gui_apps: false
    private_machine: false
    vmware_guest: false
