all:
  vars:
    ansible_ssh_extra_args: "-o IdentitiesOnly=yes -o PubKeyAuthentication=yes -o ForwardAgent=yes"
    ansible_python_interpreter: /usr/bin/python3
    # specify user for which this whole playbook should run
    target_user: "{{ lookup('env','USER') or 'konrad' }}"
    # for ssh-ingress if below is enabled
    enable_ssh: true
    home_path: "/home/{{ target_user }}"
    # path to dotfiles repository on a host (I assume all hosts are linux machines)
    repo_path: "{{ home_path }}/Code/github.com/konradmalik/dotfiles"
    # zsh files dir (same as in zshenv)
    zdotdir: "~/.config/zsh"
    # if true - assumes installation in a docker-container
    # some apps will be disabled, like the docker daemon itself
    is_docker: false
    # if enabled - some gui only apps will be installed as well
    gui_apps: false
    # if true, will autoreboot at 2 am after automatic updates
    enable_auto_reboot: false
    # versions used mostly by ubuntu tasks that install stuff from github directly
    git_versions:
      nerdctl: 0.22.2
    # Mappings from Ansible reported architecture to distro release architecture
    arch_map:
      x86_64: amd64
      ppc64le: ppc64el
      s390x: s390x
      armv7l: armhf
      aarch64: arm64

lima:
  hosts:
    devarch:
  vars:
    ansible_connection: local
    is_docker: true
    enable_auto_reboot: false
    enable_ssh: false
    gui_apps: false
    home_path: "/home/{{ target_user }}.linux"

cicd:
  hosts:
    limavm:
  vars:
    ansible_connection: local
    is_docker: false
    enable_auto_reboot: false
    enable_ssh: false
    gui_apps: false
    home_path: "/home/{{ target_user }}.linux"

local:
  hosts:
    localhost:
  vars:
    ansible_connection: local
    is_docker: false
    enable_auto_reboot: false
    enable_ssh: false
    gui_apps: false

docker:
  hosts:
    devarchd:
  vars:
    ansible_connection: local
    is_docker: true
    enable_auto_reboot: false
    enable_ssh: false
    gui_apps: false

remote:
  children:
    edge:
      children:
        rpis:
          hosts:
            rpi4-1:
            rpi4-2:
          vars:
            is_docker: false
            enable_auto_reboot: true
            enable_ssh: true
            gui_apps: false
        laptops:
          hosts:
            vaio:
            xps12:
            m3800:
              enable_auto_reboot: false
              gui_apps: true
          vars:
            is_docker: false
            enable_auto_reboot: true
            enable_ssh: true
            gui_apps: false
