all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # specify user for which this whole playbook should run
    target_user: "{{ lookup('env','USER') or 'konrad' }}"
    # for ssh-ingress if below is enabled
    enable_ssh: true
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/private.pub') }}"
    # path to dotfiles repository on a host (I assume all hosts are linux machines)
    repo_path: "/home/{{ target_user }}/Code/dotfiles"
    # zsh files dir (same as in zshenv)
    zdotdir: "~/.config/zsh"
    # if enabled - some gui only apps will be installed as well
    gui_apps: false
    # if enabled, ssh config will be linked (outbound ssh)
    private_machine: false
    # if enabled, will setup stuff needed to properly work inside a vmware guest
    vmware_guest: false
    # versions used mostly by ubuntu tasks that install stuff from github directly
    git_versions:
      asdf: 0.10.0
      docker_compose: 2.4.1
      dive: 0.10.0
      dsq: 0.15.1
      duf: 0.8.1
      earthly: 0.6.14
      k9s: 0.25.18
      kind: 0.12.0
      nvim: 0.7.0
      shfmt: 3.4.3
      tinygo: 0.22.0
      viddy: 0.3.4
    # Mappings from Ansible reported architecture to distro release architecture
    arch_map:
      x86_64: amd64
      ppc64le: ppc64el
      s390x: s390x
      armv7l: armhf
      aarch64: arm64

local:
  hosts:
    localhost:
  vars:
    ansible_connection: local
    enable_ssh: false
    private_machine: true
