all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # specify user for which this whole playbook should run
    target_user: "{{ lookup('env','USER') or 'konrad' }}"
    # for ssh-ingress if below is enabled
    enable_ssh: false
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/private.pub') }}"
    # path to dotfiles repository on a host. Replace is needed for macos compatibility
    repo_path: "{{ (playbook_dir + '/../../../../dotfiles') | realpath | replace('/Users','/home')}}"
    # zsh files dir (same as in zshenv)
    zdotdir: "~/.config/zsh"
    # if enabled - some gui only apps will be installed as well
    gui_apps: false
    # if enabled, ssh config will be linked (outbound ssh)
    private_machine: false
    # if enabled, will setup stuff needed to properly work inside a vmware guest
    vmware_guest: false
    # versions used mostly by ubuntu tasks that install stuff from github directly
    git_versions:
      asdf: 0.9.0
      broot: 1.9.3
      docker_compose: 2.3.0
      dive: 0.10.0
      dsq: 0.5.0
      duf: 0.8.1
      earthly: 0.6.10
      exa: 0.10.1
      flux: 0.27.3
      k9s: 0.25.18
      kind: 0.11.1
      git_delta: 0.12.0
      golangci_lint: 1.44.2
      gotop: 4.1.3
      hyperfine: 1.13.0
      nodejs: 17.x
      nvim: 0.6.1
      shfmt: 3.4.3
      stew: 0.3.0
      starship: 1.3.0
      tidy_viewer: 1.4.3
      tilt: 0.25.3
      tinygo: 0.22.0
      watchexec: 1.18.6
      viddy: 0.3.4
      zoxide: 0.8.0
    # Mappings from Ansible reported architecture to distro release architecture
    arch_map:
      x86_64: amd64
      ppc64le: ppc64el
      s390x: s390x
      armv7l: armhf
      aarch64: arm64

local:
  hosts:
    localhost:
  vars:
    ansible_connection: local
    private_machine: true
    gui_apps: true
