- hosts: "{{ variable_host | default('local') }}"
  gather_facts: true
  tasks:
    - name: Print my vars
      ansible.builtin.debug:
        msg: |
          is_docker: "{{ is_docker }}"
          enable_auto_reboot: "{{ enable_auto_reboot }}"
          enable_ssh: "{{ enable_ssh }}"
          gui_apps: "{{ gui_apps }}"
  roles:
    - role: aur_builder-setup
      when: ansible_distribution == "Archlinux"
    - system
    - role: unattended_upgrades
      when: not is_docker
    - rust
    #
    - role: repository
      tags: repository
    - role: nix
      when:
        - not is_docker # it requires systemd
    - role: ssh-ingress
      when:
        - enable_ssh
        - ansible_system == "Linux"
    - shell
    # macos should go through app store
    - role: tailscale
      when: ansible_system == "Linux"
    - role: docker
      when: not is_docker
    - role: alacritty
      when:
        - gui_apps
        - not is_docker
    - role: window_manager
      tags: window_manager
      when:
        - gui_apps
        - not is_docker
        - ansible_system == "Linux"
    # KEEP THIS AT THE VERY END
    - role: aur_builder-cleanup
      when: ansible_distribution == "Archlinux"
