- hosts: "{{ variable_host | default('local') }}"
  gather_facts: true
  tasks:
    - name: Print my vars
      ansible.builtin.debug:
        msg: |
          is_docker: "{{ is_docker }}"
          enable_auto_reboot: "{{ enable_auto_reboot }}"
          enable_ssh: "{{ enable_ssh }}"
          gui_apps: "{{ gui_apps }}"
          private_machine: "{{ private_machine }}"
  roles:
    - role: aur_builder-setup
      when: ansible_distribution == "Archlinux"
    - system
    - role: unattended_upgrades
      when: not is_docker
    # languages earliest possible (needed later)
    - python
    - go
    - rust
    #
    - tools
    - role: repository
      tags: repository
    - dotfiles
    - role: nix
      when:
        - not is_docker # it requires systemd
    - charm
    - git
    - role: bitwarden
      when: private_machine
    - ssh-egress
    - role: ssh-ingress
      when:
        - enable_ssh
        - ansible_system == "Linux"
    - tmux
    - neovim
    - ranger
    - shell
    - asdf
    - broot
    # macos should go through app store
    - role: tailscale
      when: ansible_system == "Linux"
    - role: docker
      when: not is_docker
    # deprecate docker once comfortable with podman
    - role: podman
      when: not is_docker
    # earthly requires docker
    - role: earthly
      when: not is_docker
    - role: kubernetes
      when: not is_docker
    - role: ansible
      when: private_machine
    - role: cloud
      when:
        - private_machine
        - not is_docker
    - role: fonts
      when:
        - gui_apps
        - not is_docker
    - role: alacritty
      when:
        - gui_apps
        - not is_docker
    - role: window_manager
      tags: window_manager
      when:
        - gui_apps
        - not is_docker
        - ansible_system == "Linux"
    - role: vscode
      when:
        - gui_apps
        - not is_docker
        - ansible_architecture == "x86_64"
    # a backup solution
    - role: restic
      when:
        - not is_docker
        - "'devarch' in inventory_hostname"
    # KEEP THIS AT THE VERY END
    - role: aur_builder-cleanup
      when: ansible_distribution == "Archlinux"
