- name: add charm apt key
  become: true
  ansible.builtin.get_url:
    url: https://repo.charm.sh/apt/gpg.key
    dest: /etc/apt/trusted.gpg.d/charm.asc
    mode: "0644"
    force: true

- name: add charm apt repo
  become: true
  apt_repository:
    repo: deb https://repo.charm.sh/apt/ * *
    state: present
    update_cache: yes

- name: install charm tools
  become: true
  apt:
    pkg:
      - glow
      - vhs
      - ttyd
      - ffmpeg
      - gum
    state: present
