- name: install yay packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - fzf
      - curl
      - bat
      - bottom
      - exa
      - fd
      - hyperfine
      - ripgrep
      # ripgrep-all and deps start
      - ripgrep-all
      - graphicsmagick
      - pandoc-bin
      - poppler
      - tesseract
      # ripgrep-all deps end
      - the_silver_searcher
      # json tools start
      - jq
      - jo
      - jc-git
      # json tools end
      - dsq
      - dust
      - zoxide
      - procs
      - nq-git
      - sshfs
      - tree
      - stow
      - up
      - viddy
      - shellcheck-bin
      - duf
      - tldr
      - ngrok
      - croc
      - bash-bats
      - watchexec
      - python-pipx
      - tidy-viewer
      - zathura-pdf-mupdf
      - unzip
      - wget
      - npm
