- name: make sure local bin folder exists
  file:
    path: ~/.local/bin
    state: directory

- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- import_tasks: ubuntu-aarch64.yaml
  when: ansible_architecture == "aarch64"

- name: install 'tidy-viewer' from cargo
  args:
    executable: /bin/bash
  environment:
    PATH: "~/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      cargo install --locked tidy-viewer
    creates: "~/.cargo/bin/tidy-viewer"

- name: install mypy from pip via pipx
  become: no
  shell:
    chdir: /tmp
    cmd: |
      ~/.local/bin/pipx install mypy || pipx install mypy
    creates: ~/.local/bin/mypy

- name: install black from pip via pipx
  become: no
  shell:
    chdir: /tmp
    cmd: |
      ~/.local/bin/pipx install black || pipx install black
    creates: ~/.local/bin/black

- name: install isort from pip via pipx
  become: no
  shell:
    chdir: /tmp
    cmd: |
      ~/.local/bin/pipx install isort || pipx install isort
    creates: ~/.local/bin/isort
