- name: make sure local bin folder exists
  file:
    path: ~/.local/bin
    state: directory

- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- import_tasks: ubuntu-aarch64.yaml
  when: ansible_architecture == "aarch64"

- name: install 'tidy-viewer' from cargo
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      cargo install --locked tidy-viewer
    creates: "~/.cargo/bin/tidy-viewer"

- name: install 'data-diff' from pip via pipx
  become: false
  environment:
    PATH: "{{ home_path }}/.local/bin:{{ ansible_env.PATH }}"
  shell:
    chdir: /tmp
    cmd: pipx install 'data-diff[all]'
    creates: ~/.local/bin/data-diff
