- name: install up from github
  become: true
  shell:
    chdir: /tmp
    cmd: |
      git clone --depth 1 https://github.com/akavel/up.git
      cd up
      go build -o /usr/local/bin/up .
    creates: /usr/local/bin/up

- name: install viddy from github
  become: true
  shell:
    chdir: /tmp
    cmd: |
      git clone --depth 1 --branch v{{ git_versions.viddy }} https://github.com/sachaos/viddy.git
      cd viddy
      go build -o /usr/local/bin/viddy .
    creates: /usr/local/bin/viddy
