- name: install apt packages
  become: yes
  apt:
    name:
      - exa
      - gdb
      - curl
      - fzf
      - fd-find
      - jq
      - jo
      - jc
      - nodejs
      - npm
      - nq
      - sshfs
      - tree
      - stow
      - bat
      - ripgrep
      - silversearcher-ag
      - shellcheck
      - tldr
      - zathura
      - bats
      - unzip
      - wget
      - zoxide
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes
    # the last one required by bat/ripgrep
    dpkg_options: "force-confdef,force-confold,force-overwrite"

- name: make sure local bin folder exists
  file:
    path: ~/.local/bin
    state: directory

- name: link fd-find to fd
  file:
    src: /usr/bin/fdfind
    path: ~/.local/bin/fd
    state: link
    force: yes

- name: link bat
  become: yes
  file:
    src: /usr/bin/batcat
    path: /usr/local/bin/bat
    state: link
    force: yes

- name: install non-classic snap packages
  become: yes
  community.general.snap:
    name:
      - procs

- name: install ngrok from snap (edge)
  become: yes
  community.general.snap:
    name: ngrok
    channel: latest/edge

- name: Install pipx from pip
  pip:
    name: pipx

- name: install duf from git releases
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -o duf.deb -L https://github.com/muesli/duf/releases/download/v{{ git_versions.duf }}/duf_{{ git_versions.duf }}_{{ ansible_system | lower }}_{{ arch_map[ansible_architecture] }}.deb
      dpkg -i duf.deb
      rm -rf duf.deb
    creates: /usr/bin/duf

- name: install 'hyperfine' from cargo
  args:
    executable: /bin/bash
  environment:
    PATH: "~/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      cargo install --locked hyperfine
    creates: "~/.cargo/bin/hyperfine"

- block:
    - name: install up from github
      become: yes
      shell:
        chdir: /tmp
        cmd: |
          curl -LO https://github.com/akavel/up/releases/latest/download/up
          chmod +x up
          mv up /usr/local/bin/
        creates: /usr/local/bin/up

    - name: install viddy from github
      become: yes
      shell:
        chdir: /tmp
        cmd: |
          curl -L https://github.com/sachaos/viddy/releases/download/v{{ git_versions.viddy }}/viddy_{{ git_versions.viddy }}_{{ ansible_system }}_{{ ansible_architecture }}.tar.gz | tar xvfz -
          chmod +x viddy
          mv viddy /usr/local/bin/
        creates: /usr/local/bin/viddy

    - name: install dsq from git (ubuntu amd64)
      become: yes
      shell:
        chdir: /tmp
        cmd: |
          curl -LO "https://github.com/multiprocessio/dsq/releases/download/{{ git_versions.dsq }}/dsq-linux-x64-{{ git_versions.dsq }}.zip"
          unzip dsq-*-{{ git_versions.dsq }}.zip
          sudo mv dsq /usr/local/bin/dsq
        creates: /usr/local/bin/dsq

  when: ansible_architecture == "x86_64"

- name: install croc
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl https://getcroc.schollz.com | bash
    creates: /usr/local/bin/croc

- name: install 'watchexec' from cargo
  args:
    executable: /bin/bash
  environment:
    PATH: "~/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      cargo install --locked watchexec-cli
    creates: "~/.cargo/bin/watchexec"

- name: install ripgrep-all deps
  become: yes
  apt:
    name:
      - pandoc
      - poppler-utils
      - ffmpeg
      - tesseract-ocr
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install 'ripgrep-all' from cargo
  args:
    executable: /bin/bash
  environment:
    PATH: "~/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      cargo install --locked ripgrep_all
    creates: ~/.cargo/bin/rga

- name: install 'dust' from cargo
  args:
    executable: /bin/bash
  environment:
    PATH: "~/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      cargo install --locked du-dust
    creates: ~/.cargo/bin/dust

- name: install 'bottom' from cargo
  args:
    executable: /bin/bash
  environment:
    PATH: "~/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      cargo install --locked bottom
    creates: ~/.cargo/bin/btm

- name: install pre-commit from pip via pipx
  become: no
  shell:
    chdir: /tmp
    cmd: |
      ~/.local/bin/pipx install pre-commit
    creates: ~/.local/bin/pre-commit
