- name: Check that dotfiles repo exists
  stat:
    path: ~/Code/dotfiles
  register: dotfiles_stat_result

- block:
    - name: Ensure dotfiles repo exists (public)
      ansible.builtin.git:
        repo: https://github.com/konradmalik/dotfiles.git
        dest: ~/Code/dotfiles
        version: main
        recursive: "no"

    - name: Ensure dotfiles repo exists (private)
      ansible.builtin.git:
        repo: git@github.com:konradmalik/dotfiles.git
        dest: ~/Code/dotfiles
        version: main
        recursive: "yes"
      when: private_machine
  when: not dotfiles_stat_result.stat.exists
