- name: install nix from script
  become: true
  args:
    executable: /bin/bash
  shell:
    cmd: yes | sh <(curl -L https://nixos.org/nix/install) --daemon
    creates: "/nix"

- name: link nix config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - nix

- name: install nix-env (direnv plugin)
  shell:
    cmd: nix-env -f '<nixpkgs>' -iA nix-direnv
    creates: ~/.nix-profile/share/nix-direnv/direnvrc

