- name: install nix from script
  become: true
  args:
    executable: /bin/bash
  shell:
    cmd: yes | sh <(curl -L https://nixos.org/nix/install) --daemon
    creates: "/nix"

# on linux make sure kvm is accessible, cross-arch builds will benefit
- block:
    - name: create udev rule to allow kvm
      copy:
        content: |
          KERNEL=="kvm", GROUP="kvm", MODE="0660"
        dest: /etc/udev/rules.d/99-kvm.rules

    - name: adding existing user "{{ target_user }}" to group "kvm"
      user:
        name: "{{ target_user }}"
        groups: [kvm]
        append: yes
  become: true
  when:
    - not is_docker
    - ansible_system == "Linux"

- name: link nix config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - nix

- name: build home flake
  shell:
    # interactive is required, as nix paths are added in zshrc and bashrc, and those are sourced only for interactive shells
    cmd: /bin/bash -i -c "nix build --no-link 'git+file://{{ repo_path }}?dir=files%2fnix%2f.config%2fnixpkgs#homeConfigurations.{{ target_user }}@{{ ansible_hostname }}.activationPackage'"

- name: activate home flake
  shell:
    # interactive is required, as nix paths are added in zshrc and bashrc, and those are sourced only for interactive shells
    # "$(nix path-info <flake-uri>#homeConfigurations.jdoe.activationPackage)"/activate
    cmd: /bin/bash -i -c "$(nix path-info git+file://{{ repo_path }}?dir=files%2fnix%2f.config%2fnixpkgs#homeConfigurations.{{ target_user }}@{{ ansible_hostname }}.activationPackage)/activate"
