- name: install nix from script
  become: true
  args:
    executable: /bin/bash
  shell:
    cmd: yes | sh <(curl -L https://nixos.org/nix/install) --daemon
    creates: "/nix"

- name: link nix config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - nix

- name: install home-env managed as a nix flake
  shell:
    # interactive is required, as nix paths are added in zshrc and bashrc, and those are sourced only for interactive shells
    # '%2F' is urlencoded '/'
    cmd: /bin/bash -i -c "nix profile install 'git+https://github.com/konradmalik/infra?dir=environments%2Fdev%2Fnix'"
    creates: ~/.nix-profile/share/nix-direnv/direnvrc
