- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: install asdf k3d plugin
  args:
    executable: /bin/bash
  shell:
    chdir: /tmp
    cmd: |
      . ~/.asdf/asdf.sh && \
      asdf plugin-add k3d && \
      asdf install k3d latest
    creates: ~/.asdf/plugins/

- name: install asdf flux2 plugin
  args:
    executable: /bin/bash
  shell:
    chdir: /tmp
    cmd: |
      . ~/.asdf/asdf.sh && \
      asdf plugin-add flux2 && \
      asdf install flux2 latest
    creates: ~/.asdf/plugins/flux2

- name: install asdf tilt plugin
  args:
    executable: /bin/bash
  shell:
    chdir: /tmp
    cmd: |
      . ~/.asdf/asdf.sh && \
      asdf plugin-add tilt && \
      asdf install tilt latest
    creates: ~/.asdf/plugins/tilt
