- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: install asdf k3d plugin
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      asdf plugin-add k3d && \
      asdf install k3d latest
    creates: ~/.asdf/plugins/k3d
  when: ansible_architecture == "x86_64"

- name: install asdf kind plugin
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      asdf plugin-add kind && \
      asdf install kind latest
    creates: ~/.asdf/plugins/kind

- name: install asdf flux2 plugin
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      asdf plugin-add flux2 && \
      asdf install flux2 latest
    creates: ~/.asdf/plugins/flux2

- name: install asdf tilt plugin
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      asdf plugin-add tilt && \
      asdf install tilt latest
    creates: ~/.asdf/plugins/tilt
  when: ansible_architecture == "x86_64"

- name: install asdf helm plugin
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      asdf plugin-add helm && \
      asdf install helm latest
    creates: ~/.asdf/plugins/helm

- name: install asdf kubectl plugin
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      asdf plugin-add kubectl && \
      asdf install kubectl latest
    creates: ~/.asdf/plugins/kubectl

- name: install asdf kustomize plugin
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      asdf plugin-add kustomize && \
      asdf install kustomize latest
    creates: ~/.asdf/plugins/kustomize

- name: install asdf kubeconform plugin
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      asdf plugin-add kubeconform && \
      asdf install kubeconform latest
    creates: ~/.asdf/plugins/kubeconform

- name: link k9s dot files
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - k9s
