- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: install asdf k3d plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add k3d
    creates: ~/.asdf/plugins/k3d
  when: ansible_architecture == "x86_64"

- name: install asdf kind plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add kind
    creates: ~/.asdf/plugins/kind

- name: install asdf flux2 plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add flux2
    creates: ~/.asdf/plugins/flux2

- name: install asdf tilt plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add tilt
    creates: ~/.asdf/plugins/tilt
  when: ansible_architecture == "x86_64"

- name: install asdf helm plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add helm
    creates: ~/.asdf/plugins/helm

- name: install asdf kubectl plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add kubectl
    creates: ~/.asdf/plugins/kubectl

- name: install asdf kustomize plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add kustomize
    creates: ~/.asdf/plugins/kustomize

- name: install asdf kubeconform plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add kubeconform
    creates: ~/.asdf/plugins/kubeconform

- name: link k9s dot files
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$XDG_CONFIG_HOME"{{ item }}
  with_items:
    - k9s
