- name: install broot from cargo
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ home_path }}/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      cargo install --locked broot
    creates: "~/.cargo/bin/broot"

- name: link broot binary
  become: yes
  file:
    # has to be full path due to 'become'
    src: "{{ home_path }}/.cargo/bin/broot"
    path: "/usr/local/bin/broot"
    state: link
    force: yes
