- name: install broot from cargo
  args:
    executable: /bin/bash
  environment:
    PATH: "~/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      cargo install broot

- name: link broot binary
  become: yes
  file:
    src: /home/{{ target_user }}/.cargo/bin/broot
    path: /usr/local/bin/broot
    state: link
    force: yes
