- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- import_tasks: linux.yaml
  when: ansible_system == "Linux" and ansible_system != "Archlinux"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- name: link earthly config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - earthly
