- name: install asdf earthly plugin
  args:
    executable: /bin/bash
  shell:
    chdir: /tmp
    cmd: |
      . ~/.asdf/asdf.sh && \
      asdf plugin-add earthly https://github.com/YR-ZR0/asdf-earthly && \
      asdf install earthly latest
    creates: ~/.asdf/plugins/earthly

- name: link earthly config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - earthly
