- name: install asdf earthly plugin
  environment:
    PATH: "{{ home_path }}/.asdf/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: asdf plugin-add earthly https://github.com/YR-ZR0/asdf-earthly
    creates: ~/.asdf/plugins/earthly

- name: link earthly config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - earthly
