- name: install go
  become: true
  apt:
    name:
      - golang
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install tiny go from git
  become: true
  shell:
    chdir: /tmp
    cmd: |
      curl -Lo tinygo.deb https://github.com/tinygo-org/tinygo/releases/download/v{{ git_versions.tinygo }}/tinygo_{{ git_versions.tinygo }}_{{ arch_map[ansible_architecture] }}.deb
      dpkg -i tinygo.deb
    creates: "/usr/local/bin/tinygo"
  when: ansible_architecture == "x86_64"
