name: Arch Linux lima test

on: [push]

jobs:
  arch-lima-up:
    runs-on: macos-latest
    env:
      MACHINE: arch
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Lima
        run: |
          set -x
          # Github runners seem to symlink to python2.7 version of 2to3,
          # breaking upgrades to latest python@3.9
          rm -f /usr/local/bin/2to3
          time brew update
          time brew install lima
          time brew upgrade

      - name: Cache ~/Library/Caches/lima/download
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/lima/download
          key: ${{ runner.os }}-${{ env.MACHINE }}

      - name: Start devarch
        run: time limactl start --name=devarch --tty=false template://archlinux

      - name: Copy files
        run: |
          set -x
          time limactl shell devarch mkdir -p /home/runner.linux/Code
          time limactl shell devarch cp -a ../infra /home/runner.linux/Code/

      - name: Install dependencies
        working-directory: ./environments/dev/ansible
        run: |
          set -x
          time limactl shell devarch sudo pacman -Sy --noconfirm ansible python python-packaging
          time limactl shell devarch ./install-dependencies.sh

      - name: Run ansible
        working-directory: ./environments/dev/ansible
        run: |
          time limactl shell devarch ansible-playbook \
              -i ./inventory.yaml \
              ./playbook.yml \
              --extra-vars "variable_host=lima" \
              --extra-vars "private_machine=false" \
              --extra-vars "ansible_become_pass=''"
