name: Ubuntu Jammy test

on: [push]

jobs:
  jammy-vagrant-up:
    runs-on: macos-10.15
    env:
      MACHINE: jammy
    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}-${{ env.MACHINE }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Show Vagrant version
        run: vagrant --version
        working-directory: ./environments/dev

      - name: Update box
        run: vagrant box update
        working-directory: ./environments/dev

      - name: Clean old boxes
        run: vagrant box prune --force
        working-directory: ./environments/dev

      - name: Run vagrant up
        run: vagrant up $MACHINE
        working-directory: ./environments/dev

      - name: ssh into box after boot
        run: vagrant ssh $MACHINE -c "echo 'hello world!'"
        working-directory: ./environments/dev
