VERSION 0.6

ARG IMAGE=archlinux:base-devel
#ARG IMAGE=ubuntu:jammy

FROM $IMAGE

jammy:
    FROM ubuntu:jammy

    RUN apt update && apt install -y ansible python3 sudo

arch:
    FROM archlinux:base-devel

    RUN pacman -Sy --noconfirm ansible python python-packaging

ansible:
    ARG USER=konrad
    ARG BASE=+arch

    FROM $BASE
    RUN echo "$USER   ALL=(ALL:ALL) ALL" > /etc/sudoers
    RUN useradd -m $USER
    USER $USER
    WORKDIR /home/$USER

    COPY --dir ./ansible .
    RUN ./ansible/install-dependencies.sh
    RUN cd ./ansible && \
        ansible-playbook \
            -i inventory.yaml \
            ./playbook.yml \
            --extra-vars "variable_host=localhost" \
            --extra-vars "ansible_become_pass=passwordless"
