VERSION 0.6

FROM scratch

jammy:
    FROM ubuntu:jammy

    RUN apt update && apt install -y ansible python3 sudo

arch:
    FROM archlinux:base-devel

    RUN pacman -Syu --noconfirm
    RUN pacman -Sy --noconfirm ansible python python-packaging openssl

ansible:
    ARG USER=konrad
    ARG BASE=+arch

    FROM $BASE
    RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/12-user-nopasswd
    RUN chmod 0440 /etc/sudoers.d/12-user-nopasswd
    RUN useradd --create-home $USER
    USER $USER
    WORKDIR /home/$USER

    RUN mkdir ./ansible
    COPY ./ansible/install-dependencies.sh ./ansible/install-dependencies.sh
    RUN ./ansible/install-dependencies.sh

    RUN set -eux; \
            mkdir ~/.ssh; \
            curl https://github.com/konradmalik.keys | tee -a ~/.ssh/authorized_keys

    COPY --dir ./ansible .
    RUN cd ./ansible && \
        ansible-playbook \
            -i ./inventory.yaml \
            ./playbook.yml \
            --extra-vars "variable_host=docker" \
            --extra-vars "ansible_become_pass=''"
